services:
  fastdl:
    image: nginx:alpine
    container_name: fastdl
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/cstrike:/usr/share/nginx/html/cstrike
      # - ./data/hl2:/usr/share/nginx/html/hl2
